module.exports = {
    apps: [
        {
            name: 'api_service',
            max_memory_restart: '500M',
            port: 3000,
            // watch: true,
            exec_mode: 'cluster',
            instances: 3,
            // autorestart: true,
            max_restarts: 1,
            script: './dist/index.js',
            // exec_interpreter: 'node_modules/.bin/babel-node',
            // script: './src/index.js',
            // env: {
            //     PORT: 3000,
            //     NODE_ENV: 'production',
            // },
            // env_production: {
            //     PORT: 3000,
            //     NODE_ENV: 'production',
            // },
        },
        {
            name: 'update-worker',
            max_memory_restart: '500M',
            // watch: true,
            exec_mode: 'cluster',
            instances: '2',
            autorestart: true,
            max_restarts: 2,
            script: './dist/product-worker.js',
        },
        {
            name: 'kafka-order-worker',
            max_memory_restart: '500M',
            exec_mode: 'cluster',
            instances: '1',
            autorestart: true,
            max_restarts: 2,
            script: './dist/rabbitmq-order-worker.js',
        },
        {
            name: 'kafka-common-worker',
            max_memory_restart: '500M',
            exec_mode: 'cluster',
            instances: '2',
            autorestart: true,
            max_restarts: 2,
            script: './dist/rabbitmq-common-worker.js',
        },
        {
            name: 'transaction-cron',
            max_memory_restart: '300M',
            exec_mode: 'fork',
            autorestart: true,
            max_restarts: 2,
            script: './dist/transaction-cron.js',
        },
        {
            name: 'promotion-cron',
            max_memory_restart: '300M',
            exec_mode: 'fork',
            autorestart: true,
            max_restarts: 2,
            script: './dist/promotion-cron.js',
        },
    ],
}
